version: '3.8'

services:

  backend:
    container_name: backend
    build: 
      context: backend
    ports:
      - '8000:8000'
    volumes:
      - './backend/app/:/var/www/app'
    env_file:
      - .env
    command: bash -c "wait-for-it --service db:5432 --timeout=15 -- uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
  
  frontend:
    container_name: frontend
    build:
      context: frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend/:/var/www/app'
    command: 
  
  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: mandacodigo
      POSTGRES_PASSWORD: mandacodigo
      POSTGRES_DB: mandacodigo
    ports:
      - "5432:5432"
    restart: always
