version: '3.8'

services:

  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile.backend
    ports:
      - '8000:8000'
    volumes:
      - './backend/:/usr/src/app'
    env_file:
      - .env
    command: [
      'wait-for-it', '--service', 'database:5432', '--', 
      'uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000', '--reload'
    ]
    restart: always
  
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend/:/usr/src/app:delegated'
      - '/usr/src/app/node_modules'
    command: ['npm', 'start']
    restart: always
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true


  database:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: mandacodigo
      POSTGRES_PASSWORD: mandacodigo
      POSTGRES_DB: mandacodigo
    ports:
      - '5432:5432'
    restart: always
